version: "3.9"
services:
  dash:
    build: .
    volumes:
      - .:/app
    ports:
      - "8050:8050"
    command: python backend/app.py
    environment:
      - PYTHONUNBUFFERED=1
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - dash