services:
  - type: web
    name: trailiq-dash
    runtime: python
    plan: free
    buildCommand:  "pip install -r backend/requirements.txt"
    startCommand:  "gunicorn --chdir backend --bind 0.0.0.0:${PORT:-10000} app:server"
    autoDeploy: true
    envVars:
      - key: PORT      
        value: 10000
